seed_everything: 42

model:
  class_path: src.models.latent_transformer.LatentTransformer
  init_args:
    first_stage_config:
    # if config_path is present, 
    # then load the model from the config and ckpt path. 
    # Otherwise, load the model from the class_path and init_args.

      config_path: ./egs/cifar10/jsa/categorical_prior_conv/2026-01-15_15-43-39/config.yaml
      ckpt_path: ./egs/cifar10/jsa/categorical_prior_conv/2026-01-15_15-43-39/checkpoints/last.ckpt

      class_path: null
      init_args: null
        # others...

    cond_stage_config:
      # mode can be first_stage_model, external_model or no_cond
      # - first_stage_model, then the cond_stage_model will be the same as the first_stage_model, 
      #   and no need to specify the class_path, init_args and ckpt_path
      # - external_model, then need to specify the class_path, init_args and ckpt_path
      #   or, we can also provide a separate config file for the external model, which contains the class_path and init_args, and then specify the ckpt_path here.
      # - no_cond, then no need to specify the above parameters, 
      #   but need to specify the sos_token for the transformer
      mode: no_cond

      config_path: null # ./configs/external_model.yaml
      ckpt_path: null
      
      class_path: src.modules.cond_encoders.SOSProvider
      init_args:
          # some args for the external model
          sos_token: 1024
      
      # if mode is no_cond, then need to specify the sos_token
      # class_path: src.models.sos_provider.SOSProvider
      # init_args:
      #     sos_token: 0

      # if mode is first_stage_model, then no need to specify the above parameters
    
    transformer:
      class_path: src.modules.gpts.mingpt.GPT
      init_args:
        # some args for the transformer net
        vocab_size: 1025
        block_size: 64
        n_layer: 6
        n_head: 4
        n_embd: 128
        embd_pdrop: 0.2
        resid_pdrop: 0.2
        attn_pdrop: 0.15

    permuter:
        class_path: src.modules.permuter.Identity
        # init_args:
          # some args for the permuter

    # The probability of keeping the original token of the input sequence, 
    # instead of replacing it with the random token, during training.
    pkeep: 0.9
    
    # The key in the dataloader batch for the conditioning stage, 
    # may be different from the image key used in the first stage model, 
    # e.g., it can be "label" for class-conditional generation
    cond_stage_dataset_key: image

    base_learning_rate: 1e-6
    weight_decay: 0.0001

data:
  class_path: src.data.cifar10.CIFAR10DataModule
  init_args:
    root: ./data/cifar10
    batch_size: 64
    num_workers: 4

trainer:
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ./egs/cifar10/latent_transformer
      
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: valid/loss
        mode: min
        save_top_k: 3
        filename: "{epoch:06}"
        save_last: true

    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: src.utils.callbacks.grad_norm_callback.GradientNorm
      init_args:
        norm_type: 2
        log_every_n_steps: 1

    - class_path: src.utils.callbacks.save_model_summary_callback.LogModelSummary
      init_args:
        max_depth: 3

    - class_path: src.utils.callbacks.image_logger_callback.ImageLogger
      init_args:
        batch_frequency: 750
        max_images: 16
        nrow: 4
        clamp: true

  max_epochs: 100000
  max_steps: 1000000 # higher priority than max_epochs
  devices: [6,7]
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false
  precision: 32
  enable_progress_bar: true # You can set it to false if you don't want to see the progress bar during training.
  log_every_n_steps: 10 # You can adjust the logging frequency according to your needs.

  
